# Generated by Django 5.2.5 on 2025-08-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
